[package]
name = "activitystreams"
description = "A set of core types and traits for activitystreams data"
version = "0.7.0-alpha.11"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://git.asonix.dog/Aardwolf/activitystreams"
documentation = "https://docs.rs/activitystreams"
readme = "README.md"
keywords = ["activitystreams", "activitypub"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "activitystreams-ext"
]

[dependencies]
chrono = "0.4"
mime = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
url = { version = "2.1", features = ["serde"] }

[dev-dependencies]
anyhow = "1.0"
