[package]
name = "build-clean"
version = "1.2.0"
edition = "2021"
license = "Apache-2.0"
description = "Clean all build caches on your disk!"
homepage = "https://codeberg.org/xtex/build-clean"
repository = "https://codeberg.org/xtex/build-clean.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
async-recursion = "1.1"
crossterm = "0.27"
cursive = { version = "0.20", features = ["crossterm-backend"] }
cursive-async-view = "0.6"
globset = "0.4.14"
mlua = { version = "0.9", features = ["lua54", "send", "serde", "macros", "mlua_derive"] }
num_cpus = "1.16"
owo-colors = "4.0"
parking_lot = "0.12"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full", "tracing"] }

[package.metadata.docs.rs]
features = ["mlua/vendored"]
rustdoc-args = ["--cfg", "docsrs"]
