baseURL = 'https://xtex.exozy.me/'
languageCode = 'zh-cn'
title = "xtex's Blog"
theme = 'arc'
paginate = 30
copyright = 'Creative Commons Attribution-ShareAlike 4.0 International License'
enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = true
rssLimit = 30
timeZone = "Asia/Shanghai"

[author]
    name = 'xtex'

[params]
    description = "xtex's personal blog"
    index_list = false

[[params.links]]
    text = "index"
    url = "/"

[[params.links]]
    text = "posts"
    url = "/post"

[[params.links]]
    text = "rss"
    url = "/post/index.xml"

[[params.links]]
    text = "archives"
    url = "/archives"

[[params.links]]
    text = "home"
    url = "https://xtexx.ml/"
    target = "_blank"

[params.icon]
    type = "image/png"
    url = "/icon.png"

[sitemap]
    changefreq = 'weekly'
    filename = 'sitemap.xml'
    priority = 0.5

[permalinks]
    post = '/:year/:month/:slugorfilename'

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
    disableXML = false
    minifyOutput = true
