hash-format = "sha256"

[[files]]
file = "CREDITS.md"
hash = "e18165ea4fbb8799401e5ce39d9c06f53afed7c61dbfd387c384b05c7674dcda"

[[files]]
file = "LICENSE"
hash = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[[files]]
file = "README.md"
hash = "b96c20095e7b886778224c2007fca60e012d41c859d67c1a1af268950c84dd4d"

[[files]]
file = "ViaFabricPlus/settings.json"
hash = "c97448bb0414342e6d0e3b3036a76fc12316e3f6b87bd3386c47c9a410869a6f"

[[files]]
file = "config/betterpingdisplay.json"
hash = "84cbc7d60663e8cf95647d7fb8f3c3a40217c07ea4c0426d4fede8dd88d4bc13"

[[files]]
file = "config/customsplashscreen.json"
hash = "deeac03dc760936d2800fee34122ebdd5dd3f2eff124e453e5d0545fb50063f4"

[[files]]
file = "config/customsplashscreen/wide_logo.png"
hash = "4441dfbc00b8967fc33b1b03f0f6aafcce04768740133b69660e87a7d1d71492"

[[files]]
file = "config/debugify.json"
hash = "6996193d411b58e087ab2c76c0a209a28d075e847ca8416cd5f3e74fe1633903"

[[files]]
file = "config/dynamicfps.toml"
hash = "3429fa956cf7b9f29667fcfc74fdc4b505d25c4ec9a237281f33ff87e2e9df23"

[[files]]
file = "config/iris.properties"
hash = "fc273072f132ab4beba18bdee72e80cce7f82775d91219b39bbff41f9ac5158c"

[[files]]
file = "config/lambdynlights.toml"
hash = "83b8c0bbd7c92d6e668155d49f5266a1537988d76866e16ff310e2faa07ad2e3"

[[files]]
file = "config/languagereload.json"
hash = "b9eb0ae31d89d6879b5da3c6b198ba58aee0400852dc569726b3b720e22f1d1a"

[[files]]
file = "config/litematica.json"
hash = "ad6fdf495f150d0090f237808fea75a6088a666951de9e88f8ce368e2ac0d33b"

[[files]]
file = "config/logcleaner.json"
hash = "8f5b042919783ab53ace20e94a89620964e275426fa3faf7aa93345dc2031ac3"

[[files]]
file = "config/modmenu.json"
hash = "5feba4460fc88646c7cfab6828322785e145086d47e87a0a50039ca82c05e606"

[[files]]
file = "config/replaymod.json"
hash = "4353e96331fed165dfd5dff9af6048eaa69393afe57167b66c162e5a29baddf5"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "421613508ff033c031b0cc83ce8d57b53d51737036be4c695a2ad60b32fd7861"

[[files]]
file = "config/seedcracker.json"
hash = "17d143a4927c024d62fa8a38a0c1c987a7b9153c7aa6cf2f6ff6f670c9b1a682"

[[files]]
file = "config/sodium-options.json"
hash = "4eb582bb7e8c3ddb7d4d9e41c0fe9206d5768cc06c351226af3f2adfa3c64785"

[[files]]
file = "config/tweakeroo.json"
hash = "b5ff1e451b60c8a5d1d626a21c0084b082859ed241804845d8d07d64438b396a"

[[files]]
file = "config/waila/waila.json"
hash = "feeab4030df2e80853826ae23bd323d1beeca183d3dc3c02b119f3a90ac36ae1"

[[files]]
file = "config/waila/waila_plugins.json"
hash = "3271c997d638f8a920d229b37fa99c5b7a3f28bf03c273158ec9b254432c4938"

[[files]]
file = "config/xaerominimap.txt"
hash = "c26ae78ad8547bb8f62aff5cfcfc7e611401e31cb9305001b6e016027026460f"

[[files]]
file = "config/xaeropatreon.txt"
hash = "519f811142b420c13dcf133196b9edd93046cf37e30c63afaf4f0e962b4fc94a"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "5f60325504ed1c87697036574a581882b92a18f89e4f7285d0242cb8d9cd1b76"

[[files]]
file = "crosshair_config.ccmcfg"
hash = "8a629984637c34c7a7893a7b9e4b42bb0a207117fa1e355ca56d157ecf7ab502"

[[files]]
file = "icon.png"
hash = "77fefa8239b559861ace41f8b9c853e65b9e7480b77551e8d71bc3c1b4610371"

[[files]]
file = "icon.svg"
hash = "7bb655575371f8b4d4b339d3b81e7c66e475ca3a33677349053fdf4723633018"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "05ac5655886661106bb34a8a898d47fd317577f7f44519693be882c7a73c64b8"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "a14f8a33991b072fcece09a03c630cbfd17bbc74a24a04f9cf537bfa5d425280"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "6869de1ca55dc09beabb3c234727e84be4d4fbdcbad2c8081c03010713f374e1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "f238e1f28f18e58f737116b13dab9716ca38b2dd84242e802d60419cc71ed737"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "cbf5544ba86d4d10262fff9c53af6c9ef05bb92d329bb02f891a5aaf3ca94631"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "6a51c7bacf8d179e11fe783804fd3687e409f34f6288e1aaceedf7261ee14006"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "86ce47da34b9a69c105e4e22058a5d6fc12448283a54a1f911c16351f096068e"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "be694b9cf9d9d2245fb0908c837f129dd9033bfb69ffe49c0e5c9dcecb580a2e"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "095a93b4f0b4e2b8fadf8359bc145cbdd83be3c5bf23432e9a5f4e54d60de5b4"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "a43e92e619450f5e1c0cd79114232a8f8ddf16892342af1c855ebcf97f877e8f"
metafile = true

[[files]]
file = "mods/click-through-architectury.pw.toml"
hash = "576bb1a9ec6003160e98bc14dfce79d9d299303d229ea8e494e428c6b13d323e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b9cc3ddd40c728549f8de8db2b211a534303018bf8c18d22871ad17f62c47118"
metafile = true

[[files]]
file = "mods/custom-crosshair-mod.pw.toml"
hash = "67be9ae420354515747eea45602857abb14904934f5e117afa5760a36e78b715"
metafile = true

[[files]]
file = "mods/custom-splash-screen.pw.toml"
hash = "f198f659f5f32d20d5a503c3599a217e6c2d3c44a139d62f5d899201fefae708"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "f0f82f41fef1fbc7d19723170410c631894de34ba0701157a1a897bac0af34d1"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "dd45b08011417dd062568cbb230369a29aff617066c7108cf4a240ccdd9a030b"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c8c6a3893859d2f0e04ebf400c8ce8b47de21cfe6097996b5dde1561e92f3c80"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "b03c0c9616b8e790ca01054d8be91c2d6b62b26e7c9262ec7b0a70fb07e6a7f5"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4eec3de8a58a6e64ea96e31781b52f70b4b33ec02a34a45f171e3a1e6697ba86"
metafile = true

[[files]]
file = "mods/fast-chest.pw.toml"
hash = "06c5fd14757e9949fc82c95bb0ca6b02e5b462a28daa840909785405998fe9e2"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "03e174cf691b52da20bd973b955fae6f3720d3d2120f9d6cc1de5fdf3180013c"
metafile = true

[[files]]
file = "mods/imblocker.pw.toml"
hash = "7e9782d0edd364770e441aaa779cb249756d0154eca2e21b795bc9bb195d21b9"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "da49262a60cebc436b9e4b7f8ab253930029ec5f9c18874a5bf7b55a4b8bc027"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "45ad54cce889a3327cc38e244b140552c8a8616068885c26f05d4edc0a0456f0"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "5945376058eb508f9a049134ed66dbc70c861d80d043441e03b10fa4338dc1e0"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "659e2447deffc797f441ed09c0b05d75138253dfacfe1479d3938e55773be4b6"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8bb36bbf7dbac0d531f6c308329109d29d95a83a2c0d972178655efd8afddf4b"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "409d820a08baf91ace8443e3abb9ef8914083b053e1e24cb989419aaef8b3f5d"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
hash = "cf8744a2896e9d00e777500b89da0f221e405e68df0fde5f95fce4f81ebd8175"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "b7d04fcd38f84af79e1733f2f4912df51f40dbd5d196f5d6bbadce586b52136b"
metafile = true

[[files]]
file = "mods/litematica-printer.pw.toml"
hash = "3aa4802505046aeeb8f9a2f13a7750cc0263cea111ab488fb28a9d71a3e47984"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "849549f8e5590a794eaf1e4e848d25f9f38c1f7e51b0f1eba6178870c11628d7"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/log-cleaner.pw.toml"
hash = "65a25b591b2afa0767de3426a944495a52721d71a7328daa3639e60dd88a04eb"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "bbb5295f893cf4e84c400325a6c0033d755d6a2773ed4e2861fe2a438aac8222"
metafile = true

[[files]]
file = "mods/mcwifipnp.pw.toml"
hash = "048f3010da02bcaba044b7eb31514518a3cafacaa35ce5cc48b5e49157d2df50"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "b89656eaf7e4404d8d2c5b1e1155aae85a839939f83cab6d1b5e791412ad5f86"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e00217e8327711e7d6acf95814212d9398499bc15cde7a3ec4ca4417393a8fbc"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6d813994b3eda187ae08b36561b60205de365852e2163f323c4c0ee283816ac6"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7ca62a9da5c2ec9f0a8bed5394021c959e90077db16b313be44f4c8736f7fbf5"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "02343a477f6f4ffd9cbedd4f93252f443c599b2f8d250037920d3a47f5756e6a"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "4f5bc996ba57f18abd2dc12801f1cbb8d06d3d115232b15d27174172f4d4004f"
metafile = true

[[files]]
file = "mods/quick_hotkeys.pw.toml"
hash = "d01901c3ddefb29da936aaf79e31a1fba298810cbae0a411bb9c0ef7486e1761"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "a1d419cad5a32a4a442b37b2e2fe2db3e761429d6ab60dd3bb79f43d36df2297"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "401489a8476901a3f5d354b1d413f88034c9d69fb0928c932d042d99f33e68fc"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "9e7c1e6cf3b81dce5a77bf5c95ed9d8e9b936b932aeadb1255245234230ced16"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "672f3809a2053eef01aea4015ca4b0d4be6c507622172c091c17833b8d2ffb39"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "ea193a0081775b5b2dda289e12578c9122294ec6b6363dbfd7c1e7b5d2dfbd71"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "217b07516517c4c01958387192143943f3e9309a0e935828f9f32af771425d66"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "7ca0983d3b7852c06f84c66b9f12da8115ff9b8ba63293cd20452377a0de726e"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "a22a3641d47822ad6b02e9ce96400c831d448981ca727e2840cfe5eeca6ccd2c"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "75b8ac35dee78b95e98d995a1d22e2b122e39425b2ab8838334b8cac849ca0f4"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "087056c9649976cf12b0d3b844d3efecc0545574157e3a951d0acf6a36ff814c"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "7c3eff18529e48a5a3ba5e73315478fa84f32bf040adca45a37b4ba5a02bccf9"
metafile = true

[[files]]
file = "mods/whoami.pw.toml"
hash = "8b35ac594bfad2fd2533849ad3f573cc1f036be47302123a3193c9009fbe4691"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "ba1c6b53100f4b5666ccd77de55a8a29daf7b5b1b961f16dcbb8127959221a61"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "fa7940ff6c6d65fede416632132a57518ab1a79e09014410932ed614ea386a70"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "f8f30afc8349f40bfbe62d21aabf6caeca2d67a8cc2778296ce758b2763c5d8d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "796239ec3e198ff16d27b144d24f813da260ee25c7342cf5487f0db0843f1c29"
metafile = true

[[files]]
file = "options.txt"
hash = "a5ef7f68669cc0f3556ed5ef70951375c21e357e6a52c6eece8f02b7a9938683"

[[files]]
file = "resourcepacks/bettersky.pw.toml"
hash = "2f88bd49fbd1a900ae7623856ba12aff85c0973813163b1b43064fde51d47034"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "1de5f2bf9632a9bfb2576a95711155fb72d4dc9825d767615465fe58cd6bd588"
metafile = true

[[files]]
file = "resourcepacks/foliage+.pw.toml"
hash = "662d7d268d602dd4c69dcff89d6ddfad9703a52f25cad852c6d9d8aa888d4b7b"
metafile = true

[[files]]
file = "resourcepacks/mcwzh-meme-resourcepack.pw.toml"
hash = "4db5eb8e38aaee5eb653e58727c0f3f33ede51d58632f1b0109f9ad478d6ca1f"
metafile = true

[[files]]
file = "resourcepacks/shiny-ores-countxd.pw.toml"
hash = "4a2fc439ba06cf87b429a7bfde61ebbdf81aa359ec0e208fdbaa9e918b4c6b18"
metafile = true

[[files]]
file = "resourcepacks/sofron-ocd.pw.toml"
hash = "843dd5cc71109d375a35aeb11093067c0825bf885e8c0147b5e93812cc240905"
metafile = true

[[files]]
file = "resourcepacks/twemojis-in-minecraft.pw.toml"
hash = "47431478d12672c51968f63100f75c9009b1be58c8c11a59775efa1745c0550a"
metafile = true

[[files]]
file = "resourcepacks/xekrsquarepattern.pw.toml"
hash = "0175738cf5dcb41d02911f1c85d3d4b9f37fffb4137df1f925c51108df8e3355"
metafile = true

[[files]]
file = "resourcepacks/xk-redstone-display.pw.toml"
hash = "664335993895dc64996b40f9418892d0267f568715e0f64e304ce567a126d6e8"
metafile = true

[[files]]
file = "shaderpacks/makeup-ultra-fast-shaders.pw.toml"
hash = "d607da4ce672251838256616b1c6db384f5f0b5d849e428ce05d852d6e9b81ae"
metafile = true
