name = "xtex's MP Pack"
author = "xtex"
version = "2.13.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d8828e941164e538516d480c1606e4cec29285987de60b8acf398eced5cefd0"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
