name: Build

on:
  push:
  workflow_dispatch:
  create:

jobs:
  build_cargo:
    name: Build with Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - run: sudo apt install protobuf-compiler

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Publish
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

  build_oci:
    name: Build with OCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt install podman

      - name: Login
        run: podman login -u xtexChooser -p ${{ secrets.OCI_REGISTRY_TOKEN }} source.moe

      - name: Build
        run: |
          podman build -t peerd .
          podman tag localhost/peerd source.moe/xtex-vnet/peerd:nightly
          podman push source.moe/xtex-vnet/peerd:nightly

      - name: Publish
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        run: |
          podman tag localhost/peerd source.moe/xtex-vnet/peerd:${{ github.ref_name }}
          podman push source.moe/xtex-vnet/peerd:${{ github.ref_name }}
          podman tag localhost/peerd source.moe/xtex-vnet/peerd:latest
          podman push source.moe/xtex-vnet/peerd:latest
